version: '3.8'

services:
  mysql_dev:
    build: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 74085751a
      MYSQL_DATABASE: Monitoramento
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    env_file:
      - .env
    ports:
      - 8282:8282
    networks:
      - mysql-compose-network

  redis:
    image: redis
    env_file:
      - .env
    command: redis-server --requirepass 74085751a
    volumes:
      - redis-data:/data/db
    networks:
      - redis-network
    ports:
      - 6379:6379
  
networks: 
  mysql-compose-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  mysql-data: {}
  redis-data: {}
